# Generated by Django 4.1.2 on 2022-12-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='articles/default.jpeg', upload_to='articles/'),
        ),
    ]
