# Generated by Django 4.1.2 on 2022-10-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profiles/default.jpeg', upload_to='profiles/'),
        ),
    ]
